spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
#              memory: 256Mi
            limits:
              cpu: "1.0"
#              memory: 256Mi
          env:
          - name: ZIPKIN_ENDPOINT
            value: "http://zipkin:9411/api/v2/spans"
